# Generated by Django 4.2.4 on 2023-08-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lastname',
            new_name='lname',
        ),
    ]
