# Generated by Django 4.2.4 on 2023-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_firstname_register_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=20)),
                ('desig', models.CharField(max_length=20)),
                ('ph', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
