# Generated by Django 4.2.4 on 2023-08-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_register1_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register1',
            old_name='ph',
            new_name='phone',
        ),
    ]
