# Generated by Django 4.2.4 on 2023-08-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_ph_register1_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register1',
        ),
    ]
