# Generated by Django 4.2.4 on 2023-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_fileupload_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=20)),
                ('audio1', models.FileField(upload_to='djangoapp/static')),
                ('video', models.CharField(max_length=20)),
                ('video1', models.FileField(upload_to='djangoapp/static')),
                ('pdf', models.CharField(max_length=20)),
                ('pdf1', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
        migrations.DeleteModel(
            name='fileupload',
        ),
    ]
