# Generated by Django 4.2.4 on 2023-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='file1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=20)),
                ('audio1', models.FileField(upload_to='djangoapp/static')),
                ('video', models.CharField(max_length=20)),
                ('video1', models.FileField(upload_to='djangoapp/static')),
                ('pdf', models.CharField(max_length=20)),
                ('pdf1', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('fileimage', models.FileField(upload_to='djangoapp/static')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
