# Generated by Django 4.2.4 on 2023-10-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_fil2_delete_file1'),
    ]

    operations = [
        migrations.CreateModel(
            name='file1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=20)),
                ('audio1', models.FileField(upload_to='djangoapp/static')),
                ('video', models.CharField(max_length=20)),
                ('video1', models.FileField(upload_to='djangoapp/static')),
                ('pdf', models.CharField(max_length=20)),
                ('pdf1', models.FileField(upload_to='djangoapp/static')),
            ],
        ),
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='fil2',
        ),
    ]
