# Generated by Django 4.2.4 on 2023-10-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_file1_models_delete_fil2'),
    ]

    operations = [
        migrations.CreateModel(
            name='filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RenameModel(
            old_name='models',
            new_name='Smodels',
        ),
    ]
